server:
  port: 8080

spring:
  application:
    name: banking-microservice

  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_banking
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: banking
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    schemas: banking
    default-schema: banking
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 2000ms

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: banking-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.portfolio.demo.dto.message"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.portfolio.demo: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Custom application properties
banking:
  account:
    number:
      prefix: "ACC"
  transaction:
    reference:
      prefix: "TXN"
  messaging:
    kafka:
      topics:
        account-created: "banking.account.created"
        transaction-created: "banking.transaction.created"
        transaction-transfer: "banking.transaction.transfer"
        partitions: 3
        replication-factor: 1
